services:
  interbotix-server:
    container_name: interbotix-server
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - ".:./InterbotixControlServer"  # Mount your application code
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - PYTHONPATH=/opt/interbotix_ws/install/lib/python3.10/site-packages:/opt/ros/humble/lib/python3.10/site-packages
    restart: unless-stopped
    stdin_open: true
    tty: true
    platform: linux/arm64