services:
  interbotix-server:
    container_name: interbotix-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    network_mode: host
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - "/dev:/dev"
      - "./src:/opt/ros/workspace/src"
      - "./install:/opt/ros/workspace/install"
      - "ros_build:/opt/ros/workspace/build"
      - "ros_log:/opt/ros/workspace/log"
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - PYTHONPATH=/opt/ros/workspace/install/lib/python3.10/site-packages:/opt/ros/humble/lib/python3.10/site-packages
    restart: unless-stopped
    stdin_open: true
    tty: true
    platform: linux/arm64

volumes:
  ros_build:
  ros_log: