[build]
baseImage = "python:3.10"

[build.env]
PYTHONUNBUFFERED = "1"

[build.install]
cmds = ["pip install -r requirements.txt"]

[build.start]
cmd = "uv run uvicorn main:app --host 0.0.0.0 --port 3000"