[project]
name = "interbotixcontrolserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "fastapi-cli>=0.0.8",
    "fastapi[standard]>=0.116.1",
]
