on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:


jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64, rpi4-widowx250]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python environment
        run: |
          echo "Installing dependencies..."
          uv sync
      
      - name: Deploy application
        run: ./scripts/deploy.sh